# Use postgres/example user/password credentials
version: '3.1'

services:

  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080